Add missing apache patch from bug #238595 (Portage version: 2.2.00.11799-prefix/svn/Linux 2.6.9-55.ELsmp x86_64)

diff --git a/www-servers/apache/files/apache-2.2.9-r1-prefix.patch b/www-servers/apache/files/apache-2.2.9-r1-prefix.patch
--- a/www-servers/apache/files/apache-2.2.9-r1-prefix.patch
+++ b/www-servers/apache/files/apache-2.2.9-r1-prefix.patch
@@ -9,9 +9,9 @@
  
  # Dynamic Shared Object (DSO) Support
  #
-@@ -76,13 +76,13 @@
+@@ -77,13 +77,13 @@
  # To know which flag to add to APACHE2_OPTS, look at the first line of the
- # the file, which will usually be an <IfDefine OPTION> where OPTIONS is the
+ # the file, which will usually be an <IfDefine OPTION> where OPTION is the
  # flag to use.
 -Include /etc/apache2/modules.d/*.conf
 +Include @GENTOO_PORTAGE_EPREFIX@/etc/apache2/modules.d/*.conf
@@ -181,6 +181,17 @@
 +	proxycachedir:   @GENTOO_PORTAGE_EPREFIX@/var/cache/apache2
  </Layout>
  
+--- patches/21_all_itk_20080105.patch
++++ patches/21_all_itk_20080105.patch
+@@ -25,7 +25,7 @@
+    MPM_SUBDIR_NAME=$MPM_NAME
+  fi
+ +
+-+if "$apache_cv_mpm" = "itk" ; then
+++if test "$apache_cv_mpm" = "itk" ; then
+ +  AC_CHECK_LIB(cap, cap_init)
+ +fi
+ +
 --- scripts/apache2-logrotate
 +++ scripts/apache2-logrotate
 @@ -1,11 +1,11 @@
@@ -197,6 +208,53 @@
 +  @GENTOO_PORTAGE_EPREFIX@/etc/init.d/apache2 reload > /dev/null 2>&1 || true
    endscript
  }
+--- init/apache2.confd
++++ init/apache2.confd
+@@ -2,7 +2,7 @@
+
+ # When you install a module it is easy to activate or deactivate the modules
+ # and other features of apache using the APACHE2_OPTS line. Every module should
+-# install a configuration in /etc/apache2/modules.d. In that file will have an
++# install a configuration in @GENTOO_PORTAGE_EPREFIX@/etc/apache2/modules.d. In that file will have an
+ # <IfDefine NNN> directive where NNN is the option to enable that module.
+ #
+ # Here are the options available in the default configuration:
+@@ -28,7 +28,7 @@
+ # will not listen for incomming connections on the approriate port.
+ #
+ #  DEFAULT_VHOST      Enables name-based virtual hosts, with the default
+-#                     virtual host being in /var/www/localhost/htdocs
++#                     virtual host being in @GENTOO_PORTAGE_EPREFIX@/var/www/localhost/htdocs
+ #  SSL_DEFAULT_VHOST  Enables default vhost for SSL (you should enable this
+ #                     when you enable SSL)
+ #
+@@ -41,22 +41,22 @@
+ # YOU HAVE BEEN WARNED.
+
+ # PID file
+-#PIDFILE=/var/run/apache2.pid
++#PIDFILE=@GENTOO_PORTAGE_EPREFIX@/var/run/apache2.pid
+
+ # timeout for startup/shutdown checks
+ #TIMEOUT=10
+
+ # ServerRoot setting
+-#SERVERROOT=/usr/lib/apache2
++#SERVERROOT=@GENTOO_PORTAGE_EPREFIX@/usr/lib/apache2
+
+ # Configuration file location
+ # - If this does NOT start with a '/', then it is treated relative to
+ # $SERVERROOT by Apache
+-#CONFIGFILE=/etc/apache2/httpd.conf
++#CONFIGFILE=@GENTOO_PORTAGE_EPREFIX@/etc/apache2/httpd.conf
+
+ # Location to log startup errors to
+ # They are normally dumped to your terminal.
+-#STARTUPERRORLOG="/var/log/apache2/startuperror.log"
++#STARTUPERRORLOG="@GENTOO_PORTAGE_EPREFIX@/var/log/apache2/startuperror.log"
+
+ # A command that outputs a formatted text version of the HTML at the URL
+ # of the command line. Designed for lynx, however other programs may work.
 --- init/apache2.initd
 +++ init/apache2.initd
 @@ -1,4 +1,4 @@
@@ -204,47 +262,47 @@
 +#!@GENTOO_PORTAGE_EPREFIX@/sbin/runscript
  # Copyright 1999-2007 Gentoo Foundation
  # Distributed under the terms of the GNU General Public License v2
- 
-@@ -17,13 +17,13 @@
- }
- 
- checkconfd() {
+
+@@ -20,13 +20,13 @@
+	PIDFILE="${PIDFILE:-@GENTOO_PORTAGE_EPREFIX@/var/run/apache2.pid}"
+	TIMEOUT=${TIMEOUT:-10}
+
 -	SERVERROOT="${SERVERROOT:-/usr/lib/apache2}"
 +	SERVERROOT="${SERVERROOT:-@GENTOO_PORTAGE_EPREFIX@/usr/lib/apache2}"
- 	if [ ! -d ${SERVERROOT} ]; then
- 		eerror "SERVERROOT does not exist: ${SERVERROOT}"
- 		return 1
- 	fi
- 
+	if [ ! -d ${SERVERROOT} ]; then
+		eerror "SERVERROOT does not exist: ${SERVERROOT}"
+		return 1
+	fi
+
 -	CONFIGFILE="${CONFIGFILE:-/etc/apache2/httpd.conf}"
 +	CONFIGFILE="${CONFIGFILE:-@GENTOO_PORTAGE_EPREFIX@/etc/apache2/httpd.conf}"
- 	[ "${CONFIGFILE#/}" = "${CONFIGFILE}" ] && CONFIGFILE="${SERVERROOT}/${CONFIGFILE}"
- 	if [ ! -r "${CONFIGFILE}" ]; then
- 		eerror "Unable to read configuration file: ${CONFIGFILE}"
-@@ -34,7 +34,7 @@
- 	APACHE2_OPTS="${APACHE2_OPTS} -f ${CONFIGFILE}"
- 	[ -n "${STARTUPERRORLOG}" ] && APACHE2_OPTS="${APACHE2_OPTS} -E ${STARTUPERRORLOG}"
- 
+	[ "${CONFIGFILE#/}" = "${CONFIGFILE}" ] && CONFIGFILE="${SERVERROOT}/${CONFIGFILE}"
+	if [ ! -r "${CONFIGFILE}" ]; then
+		eerror "Unable to read configuration file: ${CONFIGFILE}"
+@@ -37,7 +37,7 @@
+	APACHE2_OPTS="${APACHE2_OPTS} -f ${CONFIGFILE}"
+	[ -n "${STARTUPERRORLOG}" ] && APACHE2_OPTS="${APACHE2_OPTS} -E ${STARTUPERRORLOG}"
+
 -	APACHE2="/usr/sbin/apache2"
 +	APACHE2="@GENTOO_PORTAGE_EPREFIX@/usr/sbin/apache2"
  }
- 
+
  checkconfig() {
-@@ -53,7 +53,7 @@
+@@ -56,7 +56,7 @@
  start() {
- 	checkconfig || return 1
- 	ebegin "Starting apache2"
+	checkconfig || return 1
+
 -	[ -f /var/log/apache2/ssl_scache ] && rm /var/log/apache2/ssl_scache
 +	[ -f @GENTOO_PORTAGE_EPREFIX@/var/log/apache2/ssl_scache ] && rm @GENTOO_PORTAGE_EPREFIX@/var/log/apache2/ssl_scache
- 
- 	${APACHE2} ${APACHE2_OPTS} -k start
- 	eend $?
+
+	ebegin "Starting apache2"
+	${APACHE2} ${APACHE2_OPTS} -k start
 --- conf/vhosts.d/00_default_ssl_vhost.conf
 +++ conf/vhosts.d/00_default_ssl_vhost.conf
-@@ -9,11 +9,11 @@
- Listen 443
+@@ -10,11 +10,11 @@
  
  <VirtualHost _default_:443>
+	ServerName localhost
 -	Include /etc/apache2/vhosts.d/default_vhost.include
 -	ErrorLog /var/log/apache2/ssl_error_log
 +	Include @GENTOO_PORTAGE_EPREFIX@/etc/apache2/vhosts.d/default_vhost.include
@@ -256,7 +314,7 @@
  	</IfModule>
  
  	## SSL Engine Switch:
-@@ -31,7 +31,7 @@
+@@ -32,7 +32,7 @@
  	# kill -HUP will prompt again. Keep in mind that if you have both an RSA
  	# and a DSA certificate you can configure both in parallel (to also allow
  	# the use of DSA ciphers, etc.)
@@ -265,7 +323,7 @@
  	#SSLCertificateFile /etc/apache2/ssl/server-dsa.crt
  	
  	## Server Private Key:
-@@ -39,7 +39,7 @@
+@@ -40,7 +40,7 @@
  	# point at the key file. Keep in mind that if you've both a RSA and a DSA
  	# private key you can configure both in parallel (to also allow the use of
  	# DSA ciphers, etc.)
@@ -274,7 +332,7 @@
  	#SSLCertificateKeyFile /etc/apache2/ssl/server-dsa.key
  	
  	## Server Certificate Chain:
-@@ -129,7 +129,7 @@
+@@ -130,7 +130,7 @@
  		SSLOptions +StdEnvVars
  	</FilesMatch>
  
@@ -283,7 +341,7 @@
  		SSLOptions +StdEnvVars
  	</Directory>
  
-@@ -169,7 +169,7 @@
+@@ -170,7 +170,7 @@
  	# The home of a custom SSL log file. Use this when you want a compact 
  	# non-error SSL logfile on a virtual host basis.
  	<IfModule log_config_module>
@@ -294,10 +352,10 @@
  </VirtualHost>
 --- conf/vhosts.d/00_default_vhost.conf
 +++ conf/vhosts.d/00_default_vhost.conf
-@@ -36,7 +36,7 @@
- # /etc/conf.d/apache2, the first defined virtual host elsewhere will be
+@@ -37,7 +37,7 @@
  # the default.
  <VirtualHost *:80>
+	ServerName localhost
 -	Include /etc/apache2/vhosts.d/default_vhost.include
 +	Include @GENTOO_PORTAGE_EPREFIX@/etc/apache2/vhosts.d/default_vhost.include
  
@@ -305,7 +363,7 @@
  		ServerEnvironment apache apache
 --- conf/vhosts.d/default_vhost.include
 +++ conf/vhosts.d/default_vhost.include
-@@ -17,10 +17,10 @@
+@@ -9,10 +9,10 @@
  #
  # If you change this to something that isn't under /var/www then suexec
  # will no longer work.
@@ -318,7 +376,7 @@
  	# Possible values for the Options directive are "None", "All",
  	# or any combination of:
  	#   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews
-@@ -66,12 +66,12 @@
+@@ -58,12 +58,12 @@
  	# run by the server when requested rather than as documents sent to the
  	# client.  The same rules about trailing "/" apply to ScriptAlias
  	# directives as to Alias.
@@ -339,26 +397,12 @@
  <IfModule alias_module>
  <IfModule setenvif_module>
  <IfModule negotiation_module>
--AliasMatch ^/manual(?:/(?:de|en|es|fr|ja|ko|pt-br|ru))?(/.*)?$ "/usr/share/doc/apache-VERSION/manual$1"
-+AliasMatch ^/manual(?:/(?:de|en|es|fr|ja|ko|pt-br|ru))?(/.*)?$ "@GENTOO_PORTAGE_EPREFIX@/usr/share/doc/apache-VERSION/manual$1"
+-AliasMatch ^/manual(?:/(?:de|en|es|fr|ja|ko|pt-br))?(/.*)?$ "/usr/share/doc/apache-VERSION/manual$1"
++AliasMatch ^/manual(?:/(?:de|en|es|fr|ja|ko|pt-br))?(/.*)?$ "@GENTOO_PORTAGE_EPREFIX@/usr/share/doc/apache-VERSION/manual$1"
  
 -<Directory "/usr/share/doc/apache-VERSION/manual">
 +<Directory "@GENTOO_PORTAGE_EPREFIX@/usr/share/doc/apache-VERSION/manual">
  	Options Indexes
- 	AllowOverride None
- 	Order allow,deny
---- conf/modules.d/00_autoindex.conf
-+++ conf/modules.d/00_autoindex.conf
-@@ -12,9 +12,9 @@
- 
- # We include the /icons/ alias for FancyIndexed directory listings.  If
- # you do not use FancyIndexing, you may comment this out.
--Alias /icons/ "/var/www/localhost/icons/"
-+Alias /icons/ "@GENTOO_PORTAGE_EPREFIX@/var/www/localhost/icons/"
- 
--<Directory "/var/www/localhost/icons">
-+<Directory "@GENTOO_PORTAGE_EPREFIX@/var/www/localhost/icons">
- 	Options Indexes MultiViews
  	AllowOverride None
  	Order allow,deny
 --- conf/modules.d/00_error_documents.conf
@@ -375,18 +419,20 @@
  	AllowOverride None
  	Options IncludesNoExec
  	AddOutputFilter Includes html
---- conf/modules.d/00_mod_log_config.conf
-+++ conf/modules.d/00_mod_log_config.conF
-@@ -3,7 +3,7 @@
+--- conf/modules.d/00_default_settings.conf
++++ conf/modules.d/00_default_settings.conf
+@@ -67,7 +67,7 @@
  # container, error messages relating to that virtual host will be
  # logged here.  If you *do* define an error logfile for a <VirtualHost>
  # container, that host's errors will be logged there and not here.
 -ErrorLog /var/log/apache2/error_log
 +ErrorLog @GENTOO_PORTAGE_EPREFIX@/var/log/apache2/error_log
- 
+
  # LogLevel: Control the number of messages logged to the error_log.
  # Possible values include: debug, info, notice, warn, error, crit,
-@@ -31,7 +31,7 @@
+--- conf/modules.d/00_mod_log_config.conf
++++ conf/modules.d/00_mod_log_config.conf
+@@ -20,7 +20,7 @@
  # container, they will be logged here.  Contrariwise, if you *do*
  # define per-<VirtualHost> access logfiles, transactions will be
  # logged therein and *not* in this file.
@@ -406,7 +452,7 @@
  
  # AddType allows you to add to or override the MIME configuration
  # file specified in TypesConfig for specific file types.
-@@ -55,7 +55,7 @@
+@@ -49,7 +49,7 @@
  # The mod_mime_magic module allows the server to use various hints from the
  # contents of the file itself to determine its type.  The MIMEMagicFile
  # directive tells the module where the hint definitions are located.
@@ -417,15 +463,19 @@
  # vim: ts=4 filetype=apache
 --- conf/modules.d/00_mpm.conf
 +++ conf/modules.d/00_mpm.conf
-@@ -4,7 +4,7 @@
+@@ -4,10 +4,10 @@
  # identification number when it starts.
  #
- # Note that this is the default PidFile for most MPMs.
+ # DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING
 -PidFile /var/run/apache2.pid
 +PidFile @GENTOO_PORTAGE_EPREFIX@/var/run/apache2.pid
- 
+
  # The accept serialization lock file MUST BE STORED ON A LOCAL DISK.
- #LockFile /var/run/apache2.lock
+-#LockFile /var/run/apache2.lock
++#LockFile @GENTOO_PORTAGE_EPREFIX@/var/run/apache2.lock
+
+ # Only one of the below sections will be relevant on your
+ # installed httpd.  Use "/usr/sbin/apache2 -l" to find out the
 --- conf/modules.d/40_mod_ssl.conf
 +++ conf/modules.d/40_mod_ssl.conf
 @@ -52,13 +52,13 @@
